/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package compsi.crlv.view;

import javax.swing.ButtonGroup;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author allan
 */
public class JIFLeitora extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFConectarLeitora
     */
    public JIFLeitora() {
        initComponents();
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pcscProtocolTransportGroup = new javax.swing.ButtonGroup();
        pcscReadersComboBox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaConsole = new javax.swing.JTextArea();
        protocolT0Radio = new javax.swing.JRadioButton();
        protocolT1Radio = new javax.swing.JRadioButton();
        btConectar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        pcscReadersComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcscReadersComboBoxActionPerformed(evt);
            }
        });

        jTextAreaConsole.setColumns(20);
        jTextAreaConsole.setRows(5);
        jScrollPane1.setViewportView(jTextAreaConsole);

        pcscProtocolTransportGroup.add(protocolT0Radio);
        protocolT0Radio.setSelected(true);
        protocolT0Radio.setText("T=0");
        protocolT0Radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                protocolT0RadioActionPerformed(evt);
            }
        });

        pcscProtocolTransportGroup.add(protocolT1Radio);
        protocolT1Radio.setText("T=1");
        protocolT1Radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                protocolT1RadioActionPerformed(evt);
            }
        });

        btConectar.setText("Conectar");
        btConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConectarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pcscReadersComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(protocolT0Radio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(protocolT1Radio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btConectar)))
                .addGap(0, 25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pcscReadersComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(protocolT0Radio)
                    .addComponent(protocolT1Radio)
                    .addComponent(btConectar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(0, 0, 464, 270);
    }// </editor-fold>//GEN-END:initComponents

    
    private void pcscReadersComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcscReadersComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pcscReadersComboBoxActionPerformed

    private void protocolT1RadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_protocolT1RadioActionPerformed
        // TODO add your handling code here:
        protocolT1Radio.setSelected(true);
        protocolT0Radio.setSelected(false);
    }//GEN-LAST:event_protocolT1RadioActionPerformed

    private void protocolT0RadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_protocolT0RadioActionPerformed
        // TODO add your handling code here:
        protocolT0Radio.setSelected(true);
        protocolT1Radio.setSelected(false);
    }//GEN-LAST:event_protocolT0RadioActionPerformed

    private void btConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConectarActionPerformed
        // TODO add your handling code here:
//         String transportProtocol = "";
//        String resultado;
//
//        if (btConectar.getText().equals("Conectar")) {
//
//            Enumeration<AbstractButton> elements = pcscProtocolTransportGroup.getElements();
//
//            while (elements.hasMoreElements()) {
//                JRadioButton radio = (JRadioButton) elements.nextElement();
//
//                if (radio.isSelected()) {
//                    transportProtocol = radio.getText();
//                }
//            }
//            try {
//
//                CommandProcessor.process("connect " + pcscReadersComboBox.getSelectedIndex() + " " + transportProtocol);
//
//                btConectar.setText("Desconectar");
//
//                Cursor hourglassCursor = new Cursor(Cursor.WAIT_CURSOR);
//                setCursor(hourglassCursor);
//
//                resultado = Select_APPL();
//                this.setVisible(false);
////                JDialog_Docs_Manager jDialog_Docs_Manager = new JDialog_Docs_Manager(this,true);
////                jDialog_Docs_Manager.setLocationRelativeTo(null);
////                jDialog_Docs_Manager.setVisible(true);
//                
//
//                Cursor normalCursor = new Cursor(Cursor.DEFAULT_CURSOR);
//                setCursor(normalCursor);
//
//            } catch (Exception ex) {
//                Logger.getLogger(MainGui.class.getName()).log(Level.SEVERE, null, ex);
//                ex.getMessage();
//                ex.getLocalizedMessage();
//            }
//
//        } else if (btConectar.getText().equals("Desconectar")) {
//            try {
//                CommandProcessor.process("disconnect");
//            } catch (Exception ex) {
//                Logger.getLogger(MainGui.class.getName()).log(Level.SEVERE, null, ex);
//            }
//
//            btConectar.setText("Conectar");
//        }
    }//GEN-LAST:event_btConectarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConectar;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTextArea jTextAreaConsole;
    private javax.swing.ButtonGroup pcscProtocolTransportGroup;
    private javax.swing.JComboBox pcscReadersComboBox;
    private javax.swing.JRadioButton protocolT0Radio;
    private javax.swing.JRadioButton protocolT1Radio;
    // End of variables declaration//GEN-END:variables

    public static void main(String args[]) {
        String setProperty = System.setProperty("sun.security.smartcardio.t0GetResponse", "false");
        //     System.out.println("setProperty "+setProperty);
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JIFLeitora().setVisible(true);

            }
        });
    }
      

    public static JTextArea getConsole() {
        return jTextAreaConsole;
    }

    public JButton getBtConectar() {
        return btConectar;
    }

    public void setBtConectar(JButton btConectar) {
        this.btConectar = btConectar;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public static JTextArea getjTextAreaConsole() {
        return jTextAreaConsole;
    }

    public static void setjTextAreaConsole(JTextArea jTextAreaConsole) {
        JIFLeitora.jTextAreaConsole = jTextAreaConsole;
    }

    public ButtonGroup getPcscProtocolTransportGroup() {
        return pcscProtocolTransportGroup;
    }

    public void setPcscProtocolTransportGroup(ButtonGroup pcscProtocolTransportGroup) {
        this.pcscProtocolTransportGroup = pcscProtocolTransportGroup;
    }

    public JComboBox getPcscReadersComboBox() {
        return pcscReadersComboBox;
    }

    public void setPcscReadersComboBox(JComboBox pcscReadersComboBox) {
        this.pcscReadersComboBox = pcscReadersComboBox;
    }

    public JRadioButton getProtocolT0Radio() {
        return protocolT0Radio;
    }

    public void setProtocolT0Radio(JRadioButton protocolT0Radio) {
        this.protocolT0Radio = protocolT0Radio;
    }

    public JRadioButton getProtocolT1Radio() {
        return protocolT1Radio;
    }

    public void setProtocolT1Radio(JRadioButton protocolT1Radio) {
        this.protocolT1Radio = protocolT1Radio;
    }
    
    

}
