/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package compsi.crlv.view;

import compsi.crlv.controller.ControllerLeitora;
import pkcs11_lea.MainGui;

/**
 *
 * @author allan
 */
public class MainWondow extends javax.swing.JFrame {

    /**
     * Creates new form MainWondow
     */
    public MainWondow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JDesktopPane();
        mbMainWindow = new javax.swing.JMenuBar();
        menuLeitora = new javax.swing.JMenu();
        menuConectarLeitora = new javax.swing.JMenuItem();
        menuCrlv = new javax.swing.JMenu();
        miFormularioCrlv = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuLeitora.setText("Leitora");

        menuConectarLeitora.setText("Conectar");
        menuConectarLeitora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuConectarLeitoraActionPerformed(evt);
            }
        });
        menuLeitora.add(menuConectarLeitora);

        mbMainWindow.add(menuLeitora);

        menuCrlv.setText("CRLV");

        miFormularioCrlv.setText("Formulário CRLV");
        miFormularioCrlv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFormularioCrlvActionPerformed(evt);
            }
        });
        menuCrlv.add(miFormularioCrlv);

        mbMainWindow.add(menuCrlv);

        setJMenuBar(mbMainWindow);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 773, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miFormularioCrlvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFormularioCrlvActionPerformed
        // TODO add your handling code here:
        JIFCrlv f = new JIFCrlv();
        desktop.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_miFormularioCrlvActionPerformed

    private void menuConectarLeitoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConectarLeitoraActionPerformed
        // TODO add your handling code here:
        //String setProperty = System.setProperty("sun.security.smartcardio.t0GetResponse", "false");
        JIFLeitora con = new JIFLeitora();
        ControllerLeitora conl = new ControllerLeitora(con);
        desktop.add(con);
        //con.setLocation(null);
        con.setVisible(true);
    }//GEN-LAST:event_menuConectarLeitoraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWondow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWondow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWondow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWondow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWondow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenuBar mbMainWindow;
    private javax.swing.JMenuItem menuConectarLeitora;
    private javax.swing.JMenu menuCrlv;
    private javax.swing.JMenu menuLeitora;
    private javax.swing.JMenuItem miFormularioCrlv;
    // End of variables declaration//GEN-END:variables
}
