/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package compsi.crlv.view;

import compsi.crlv.model.ModelCRLV;
import compsi.crlv.model.ModelIPVA;
import javax.swing.JButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author allan
 */
public class ViewCrlv extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFFormularioCrlv
     */
    public ViewCrlv() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelIpva = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        txtCotaUnica = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtVencCotaUnica = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtFaixaIpva = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txtParcelamentoCotas = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        txtParcela1 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtParcela2 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtParcela3 = new javax.swing.JTextField();
        panelObservacoes = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtObservacoes = new javax.swing.JTextArea();
        txtVia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCodRenavam = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRntrc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtExercicio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCpfCnpj = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        txtUfPlaca = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPlacaAnt = new javax.swing.JTextField();
        txtUfPlacaAnt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtChassi = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCombustivel = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtEspecie = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtAnoFab = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtAnoMod = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtCategoria = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtCap = new javax.swing.JTextField();
        txtPot = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtCil = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtCor = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        txtPremioTarifario = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        txtIof = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtPremioTotal = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtDataPagamento = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtLocal = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        btSalvar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setTitle("Formulário CRLV");

        panelIpva.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "IPVA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jLabel21.setText("Cota Única");

        jLabel22.setText("Venc Cota Única");

        jLabel23.setText("Faixa IPVA");

        txtFaixaIpva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFaixaIpvaActionPerformed(evt);
            }
        });

        jLabel24.setText("Pancelamento");

        jLabel25.setText("1º Cota");

        jLabel26.setText("2º Cota");

        jLabel27.setText("3º Cota");

        javax.swing.GroupLayout panelIpvaLayout = new javax.swing.GroupLayout(panelIpva);
        panelIpva.setLayout(panelIpvaLayout);
        panelIpvaLayout.setHorizontalGroup(
            panelIpvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIpvaLayout.createSequentialGroup()
                .addGroup(panelIpvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIpvaLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCotaUnica, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIpvaLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtParcelamentoCotas, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIpvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelIpvaLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtVencCotaUnica, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFaixaIpva))
                    .addGroup(panelIpvaLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtParcela1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtParcela2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtParcela3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelIpvaLayout.setVerticalGroup(
            panelIpvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelIpvaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelIpvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtCotaUnica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(txtVencCotaUnica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(txtFaixaIpva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelIpvaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txtParcelamentoCotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(txtParcela1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(txtParcela2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(txtParcela3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelObservacoes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Observações", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        txtObservacoes.setColumns(20);
        txtObservacoes.setRows(5);
        jScrollPane2.setViewportView(txtObservacoes);

        javax.swing.GroupLayout panelObservacoesLayout = new javax.swing.GroupLayout(panelObservacoes);
        panelObservacoes.setLayout(panelObservacoesLayout);
        panelObservacoesLayout.setHorizontalGroup(
            panelObservacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelObservacoesLayout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addGap(0, 0, 0))
        );
        panelObservacoesLayout.setVerticalGroup(
            panelObservacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelObservacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE))
        );

        txtVia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViaActionPerformed(evt);
            }
        });

        jLabel1.setText("VIA");

        jLabel2.setText("RENAVAM");

        txtCodRenavam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodRenavamActionPerformed(evt);
            }
        });

        jLabel3.setText("R.N.T.R.C");

        jLabel4.setText("Exercício");

        txtExercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExercicioActionPerformed(evt);
            }
        });

        jLabel5.setText("Nome");

        jLabel6.setText("CPF/CNPJ");

        txtCpfCnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCpfCnpjActionPerformed(evt);
            }
        });

        jLabel7.setText("Placa");

        jLabel8.setText("Placa Ant.");

        jLabel9.setText("Chassi");

        jLabel10.setText("Combustível");

        jLabel11.setText("Espécie/Tipo");

        txtEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEspecieActionPerformed(evt);
            }
        });

        jLabel12.setText("Marca");

        txtMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaActionPerformed(evt);
            }
        });

        jLabel13.setText("Modelo");

        jLabel14.setText("Ano Fab.");

        txtAnoFab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnoFabActionPerformed(evt);
            }
        });

        jLabel15.setText("Ano Mod.");

        jLabel16.setText("Categoria");

        jLabel17.setText("Capacidade");

        jLabel18.setText("Potencia");

        jLabel19.setText("Cilindradas");

        jLabel20.setText("Cor");

        jLabel28.setText("Premio Tarifário");

        jLabel29.setText("IOF");

        jLabel30.setText("Premio Total");

        jLabel31.setText("Data Pag.");

        jLabel32.setText("Local");

        jLabel33.setText("Data");

        btSalvar.setText("Salvar");

        btCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPremioTarifario, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIof, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPremioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btCancelar))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(panelObservacoes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(panelIpva, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel32)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel33)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel17)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtCap, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(12, 12, 12)
                                                .addComponent(jLabel19)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtCil, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel18)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtPot, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel13)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel16))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtUfPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jLabel8)
                                                        .addGap(8, 8, 8)
                                                        .addComponent(txtPlacaAnt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtUfPlacaAnt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(28, 28, 28)
                                                                .addComponent(jLabel12))
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel10)))
                                                        .addGap(4, 4, 4)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(txtCombustivel, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                                            .addComponent(txtMarca)))
                                                    .addComponent(txtNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(44, 44, 44)
                                                .addComponent(jLabel20)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtCor))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(23, 23, 23)
                                                        .addComponent(jLabel9))
                                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addGap(10, 10, 10)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtCpfCnpj)
                                                    .addComponent(txtChassi)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel11)
                                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtEspecie)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(txtAnoFab, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jLabel15)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(txtAnoMod, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(0, 0, Short.MAX_VALUE))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtExercicio, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(0, 7, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtVia, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodRenavam, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRntrc, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtVia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodRenavam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRntrc)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txtExercicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUfPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(txtPlacaAnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUfPlacaAnt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)
                                    .addComponent(txtCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel16)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19)
                            .addComponent(txtCil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)
                            .addComponent(txtPot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtCpfCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtChassi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAnoFab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(txtAnoMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelIpva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(txtPremioTarifario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29)
                    .addComponent(txtIof)
                    .addComponent(jLabel30)
                    .addComponent(txtPremioTotal)
                    .addComponent(jLabel31)
                    .addComponent(txtDataPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(panelObservacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(txtLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btCancelar))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodRenavamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodRenavamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodRenavamActionPerformed

    private void txtCpfCnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCpfCnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCpfCnpjActionPerformed

    private void txtAnoFabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnoFabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnoFabActionPerformed

    private void txtViaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtViaActionPerformed

    private void txtEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEspecieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEspecieActionPerformed

    private void txtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaActionPerformed

    private void txtFaixaIpvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFaixaIpvaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFaixaIpvaActionPerformed

    private void txtExercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExercicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExercicioActionPerformed

    
   

    public JTextField getTxtAnoFab() {
        return txtAnoFab;
    }

    public void setTxtAnoFab(JTextField txtAnoFab) {
        this.txtAnoFab = txtAnoFab;
    }

    public JTextField getTxtAnoMod() {
        return txtAnoMod;
    }

    public void setTxtAnoMod(JTextField txtAnoMod) {
        this.txtAnoMod = txtAnoMod;
    }

    public JTextField getTxtCap() {
        return txtCap;
    }

    public void setTxtCap(JTextField txtCap) {
        this.txtCap = txtCap;
    }

    public JTextField getTxtCategoria() {
        return txtCategoria;
    }

    public void setTxtCategoria(JTextField txtCategoria) {
        this.txtCategoria = txtCategoria;
    }

    public JTextField getTxtChassi() {
        return txtChassi;
    }

    public void setTxtChassi(JTextField txtChassi) {
        this.txtChassi = txtChassi;
    }

    public JTextField getTxtCil() {
        return txtCil;
    }

    public void setTxtCil(JTextField txtCil) {
        this.txtCil = txtCil;
    }

    public JTextField getTxtCodRenavam() {
        return txtCodRenavam;
    }

    public void setTxtCodRenavam(JTextField txtCodRenavam) {
        this.txtCodRenavam = txtCodRenavam;
    }

    public JTextField getTxtCombustivel() {
        return txtCombustivel;
    }

    public void setTxtCombustivel(JTextField txtCombustivel) {
        this.txtCombustivel = txtCombustivel;
    }

    public JTextField getTxtCor() {
        return txtCor;
    }

    public void setTxtCor(JTextField txtCor) {
        this.txtCor = txtCor;
    }

    public JTextField getTxtCotaUnica() {
        return txtCotaUnica;
    }

    public void setTxtCotaUnica(JTextField txtCotaUnica) {
        this.txtCotaUnica = txtCotaUnica;
    }

    public JTextField getTxtCpfCnpj() {
        return txtCpfCnpj;
    }

    public void setTxtCpfCnpj(JTextField txtCpfCnpj) {
        this.txtCpfCnpj = txtCpfCnpj;
    }

    public JTextField getTxtData() {
        return txtData;
    }

    public void setTxtData(JTextField txtData) {
        this.txtData = txtData;
    }

    public JTextField getTxtDataPagamento() {
        return txtDataPagamento;
    }

    public void setTxtDataPagamento(JTextField txtDataPagamento) {
        this.txtDataPagamento = txtDataPagamento;
    }

    public JTextField getTxtEspecie() {
        return txtEspecie;
    }

    public void setTxtEspecie(JTextField txtEspecie) {
        this.txtEspecie = txtEspecie;
    }

    public JTextField getTxtExercicio() {
        return txtExercicio;
    }

    public void setTxtExercicio(JTextField txtExercicio) {
        this.txtExercicio = txtExercicio;
    }

    public JTextField getTxtFaixaIpva() {
        return txtFaixaIpva;
    }

    public void setTxtFaixaIpva(JTextField txtFaixaIpva) {
        this.txtFaixaIpva = txtFaixaIpva;
    }

    public JTextField getTxtIof() {
        return txtIof;
    }

    public void setTxtIof(JTextField txtIof) {
        this.txtIof = txtIof;
    }

    public JTextField getTxtLocal() {
        return txtLocal;
    }

    public void setTxtLocal(JTextField txtLocal) {
        this.txtLocal = txtLocal;
    }

    public JTextField getTxtMarca() {
        return txtMarca;
    }

    public void setTxtMarca(JTextField txtMarca) {
        this.txtMarca = txtMarca;
    }

    public JTextField getTxtModelo() {
        return txtModelo;
    }

    public void setTxtModelo(JTextField txtModelo) {
        this.txtModelo = txtModelo;
    }

    public JTextField getTxtNome() {
        return txtNome;
    }

    public void setTxtNome(JTextField txtNome) {
        this.txtNome = txtNome;
    }

    public JTextArea getTxtObservacoes() {
        return txtObservacoes;
    }

    public void setTxtObservacoes(JTextArea txtObservacoes) {
        this.txtObservacoes = txtObservacoes;
    }

    public JTextField getTxtParcela1() {
        return txtParcela1;
    }

    public void setTxtParcela1(JTextField txtParcela1) {
        this.txtParcela1 = txtParcela1;
    }

    public JTextField getTxtParcela2() {
        return txtParcela2;
    }

    public void setTxtParcela2(JTextField txtParcela2) {
        this.txtParcela2 = txtParcela2;
    }

    public JTextField getTxtParcela3() {
        return txtParcela3;
    }

    public void setTxtParcela3(JTextField txtParcela3) {
        this.txtParcela3 = txtParcela3;
    }

    public JTextField getTxtParcelamentoCotas() {
        return txtParcelamentoCotas;
    }

    public void setTxtParcelamentoCotas(JTextField txtParcelamentoCotas) {
        this.txtParcelamentoCotas = txtParcelamentoCotas;
    }

    public JTextField getTxtPlaca() {
        return txtPlaca;
    }

    public void setTxtPlaca(JTextField txtPlaca) {
        this.txtPlaca = txtPlaca;
    }

    public JTextField getTxtPlacaAnt() {
        return txtPlacaAnt;
    }

    public void setTxtPlacaAnt(JTextField txtPlacaAnt) {
        this.txtPlacaAnt = txtPlacaAnt;
    }

    public JTextField getTxtPot() {
        return txtPot;
    }

    public void setTxtPot(JTextField txtPot) {
        this.txtPot = txtPot;
    }

    public JTextField getTxtPremioTarifario() {
        return txtPremioTarifario;
    }

    public void setTxtPremioTarifario(JTextField txtPremioTarifario) {
        this.txtPremioTarifario = txtPremioTarifario;
    }

    public JTextField getTxtPremioTotal() {
        return txtPremioTotal;
    }

    public void setTxtPremioTotal(JTextField txtPremioTotal) {
        this.txtPremioTotal = txtPremioTotal;
    }

    public JTextField getTxtRntrc() {
        return txtRntrc;
    }

    public void setTxtRntrc(JTextField txtRntrc) {
        this.txtRntrc = txtRntrc;
    }

    public JTextField getTxtUfPlaca() {
        return txtUfPlaca;
    }

    public void setTxtUfPlaca(JTextField txtUfPlaca) {
        this.txtUfPlaca = txtUfPlaca;
    }

    public JTextField getTxtUfPlacaAnt() {
        return txtUfPlacaAnt;
    }

    public void setTxtUfPlacaAnt(JTextField txtUfPlacaAnt) {
        this.txtUfPlacaAnt = txtUfPlacaAnt;
    }

    public JTextField getTxtVencCotaUnica() {
        return txtVencCotaUnica;
    }

    public void setTxtVencCotaUnica(JTextField txtVencCotaUnica) {
        this.txtVencCotaUnica = txtVencCotaUnica;
    }

    public JTextField getTxtVia() {
        return txtVia;
    }

    public void setTxtVia(JTextField txtVia) {
        this.txtVia = txtVia;
    }

    public JButton getBtSalvar() {
        return btSalvar;
    }
    
    public ModelCRLV getModelCrlv(ModelCRLV crlv, String action){
        ModelIPVA ipva = new ModelIPVA();
        if(action.equals("editar"))    
            ipva.setIdIpva(crlv.getIpva().getIdIpva());
        
        crlv.setVia(Integer.parseInt(txtVia.getText()));
        crlv.setCodRenavam(txtCodRenavam.getText());
        crlv.setRntrc(txtRntrc.getText());
        crlv.setExercicio(txtExercicio.getText());
        crlv.setNome(txtNome.getText());
        crlv.setCpfCnpj(txtCpfCnpj.getText());
        crlv.setPlaca(txtPlaca.getText());
        crlv.setUfPlaca(txtUfPlaca.getText());
        crlv.setPlacaAnt(txtPlacaAnt.getText());
        crlv.setUfPlacaAnt(txtUfPlacaAnt.getText());
        crlv.setChassi(txtChassi.getText());
        crlv.setEspecieTipo(txtEspecie.getText());
        crlv.setCombustivel(txtCombustivel.getText());
        crlv.setMarca(txtMarca.getText());
        crlv.setModelo(txtModelo.getText());
        crlv.setAnoFab(Integer.parseInt(txtAnoFab.getText()));
        crlv.setAnoMod(Integer.parseInt(txtAnoMod.getText()));
        crlv.setCap(txtCap.getText());
        crlv.setPot(txtPot.getText());
        crlv.setCil(txtCil.getText());
        crlv.setCategoria(txtCategoria.getText());
        crlv.setCor(txtCor.getText());
        ipva.setCotaUnica(txtCotaUnica.getText());
        ipva.setFaixaIpva(txtFaixaIpva.getText().toString());
        ipva.setVencCotaUnica(txtVencCotaUnica.getText().toString());
        ipva.setParcelamentoCotas(txtParcelamentoCotas.getText().toString());
        ipva.setVencPrimeiraCota(txtParcela1.getText().toString());
        ipva.setVencSegundaCota(txtParcela2.getText().toString());
        ipva.setVencTerceiraCota(txtParcela3.getText().toString());
        crlv.setIpva(ipva);
        /*crlv.getIpva().setFaixaIpva(txtFaixaIpva.getText());
        crlv.getIpva().setCotaUnica(txtCotaUnica.getText());
        crlv.getIpva().setVencCotaUnica(txtVencCotaUnica.getText());
        crlv.getIpva().setParcelamentoCotas(txtParcelamentoCotas.getText());
        crlv.getIpva().setVencPrimeiraCota(txtParcela1.getText());
        crlv.getIpva().setVencSegundaCota(txtParcela2.getText());
        crlv.getIpva().setVencTerceiraCota(txtParcela3.getText());
        crlv.setPremioTarifario(txtPremioTarifario.getText());*/
        crlv.setIof(txtIof.getText());
        crlv.setPremioTotal(txtPremioTotal.getText());
        crlv.setDataPag(txtDataPagamento.getText());
        crlv.setObservacoes(txtObservacoes.getText());
        crlv.setLocal(txtLocal.getText());
        crlv.setData(txtData.getText());
        
        System.out.println(txtCotaUnica.getText().toString());
                
        return crlv;
    }
    
    public void setModelCrlv(ModelCRLV crlv){
        txtVia.setText(crlv.getVia().toString());
        txtCodRenavam.setText(crlv.getCodRenavam());
        txtRntrc.setText(crlv.getRntrc());
        txtExercicio.setText(crlv.getExercicio());
        txtNome.setText(crlv.getNome());
        txtCpfCnpj.setText(crlv.getCpfCnpj());
        txtPlaca.setText(crlv.getPlaca());
        txtUfPlaca.setText(crlv.getUfPlaca());
        txtPlacaAnt.setText(crlv.getPlacaAnt());
        txtUfPlacaAnt.setText(crlv.getUfPlacaAnt());
        txtChassi.setText(crlv.getChassi());
        txtEspecie.setText(crlv.getEspecieTipo());
        txtCombustivel.setText(crlv.getCombustivel());
        txtMarca.setText(crlv.getMarca());
        txtModelo.setText(crlv.getModelo());
        txtAnoFab.setText(crlv.getAnoFab().toString());
        txtAnoMod.setText(crlv.getAnoMod().toString());
        txtCap.setText(crlv.getCap());
        txtPot.setText(crlv.getPot());
        txtCil.setText(crlv.getCil());
        txtCategoria.setText(crlv.getCategoria());
        txtCor.setText(crlv.getCor());
        txtCotaUnica.setText(crlv.getIpva().getCotaUnica());
        txtParcelamentoCotas.setText(crlv.getIpva().getParcelamentoCotas());
        txtFaixaIpva.setText(crlv.getIpva().getFaixaIpva());
        txtVencCotaUnica.setText(crlv.getIpva().getVencCotaUnica());
        txtParcela1.setText(crlv.getIpva().getVencPrimeiraCota());
        txtParcela2.setText(crlv.getIpva().getVencSegundaCota());
        txtParcela3.setText(crlv.getIpva().getVencTerceiraCota());
        txtPremioTarifario.setText(crlv.getPremioTarifario());
        txtIof.setText(crlv.getIof());
        txtPremioTotal.setText(crlv.getPremioTotal());
        txtDataPagamento.setText(crlv.getDataPag());
        txtObservacoes.setText(crlv.getObservacoes());
        txtLocal.setText(crlv.getLocal());
        txtData.setText(crlv.getData());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelIpva;
    private javax.swing.JPanel panelObservacoes;
    private javax.swing.JTextField txtAnoFab;
    private javax.swing.JTextField txtAnoMod;
    private javax.swing.JTextField txtCap;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtChassi;
    private javax.swing.JTextField txtCil;
    private javax.swing.JTextField txtCodRenavam;
    private javax.swing.JTextField txtCombustivel;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtCotaUnica;
    private javax.swing.JTextField txtCpfCnpj;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtDataPagamento;
    private javax.swing.JTextField txtEspecie;
    private javax.swing.JTextField txtExercicio;
    private javax.swing.JTextField txtFaixaIpva;
    private javax.swing.JTextField txtIof;
    private javax.swing.JTextField txtLocal;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextArea txtObservacoes;
    private javax.swing.JTextField txtParcela1;
    private javax.swing.JTextField txtParcela2;
    private javax.swing.JTextField txtParcela3;
    private javax.swing.JTextField txtParcelamentoCotas;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtPlacaAnt;
    private javax.swing.JTextField txtPot;
    private javax.swing.JTextField txtPremioTarifario;
    private javax.swing.JTextField txtPremioTotal;
    private javax.swing.JTextField txtRntrc;
    private javax.swing.JTextField txtUfPlaca;
    private javax.swing.JTextField txtUfPlacaAnt;
    private javax.swing.JTextField txtVencCotaUnica;
    private javax.swing.JTextField txtVia;
    // End of variables declaration//GEN-END:variables
}
