
package compsi.crlv.view.signer;

import compsi.crlv.model.ModelSigner;
import compsi.crlv.view.signer.utils.CertificateRenderer;
import compsi.icpbrasil.ICPBrasilConfig;
import compsi.icpbrasil.ICPBrasilSigner;
import compsi.icpbrasil.ICPBrasilStore;
import java.security.KeyStoreException;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JToggleButton;

/**
 *
 * @author allan
 */
public class ViewSigner extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewSigner
     */
    protected ModelSigner model;
    protected List<ICPBrasilSigner> signers;
    public ViewSigner(ModelSigner m) throws KeyStoreException {
       ICPBrasilConfig config = ICPBrasilStore.getInstance().getConfig();
       this.model = m;
       signers = org.jdesktop.observablecollections.ObservableCollections.observableList(ICPBrasilStore.getInstance().getSigners());
        //System.out.println(model.getSigners().get(0));
       initComponents();
    }

    public List<ICPBrasilSigner> getSigners() {
        return signers;
    }

    public void setSigners(List<ICPBrasilSigner> signers) {
        this.signers = signers;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        certificateList = new javax.swing.JList();
        btAssinar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Lista de Certificados");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Certificados"));

        certificateList.setModel(new DefaultListModel());
        certificateList.setCellRenderer(new CertificateRenderer());

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${signers}");
        org.jdesktop.swingbinding.JListBinding jListBinding = org.jdesktop.swingbinding.SwingBindings.createJListBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, certificateList);
        jListBinding.setDetailBinding(org.jdesktop.beansbinding.ELProperty.create("${certificate}"));
        bindingGroup.addBinding(jListBinding);

        certificateList.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                certificateListAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(certificateList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
        );

        btAssinar.setText("Assinar");

        btCancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btAssinar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCancelar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAssinar)
                    .addComponent(btCancelar))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-513)/2, (screenSize.height-344)/2, 513, 344);
    }// </editor-fold>//GEN-END:initComponents

    private void certificateListAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_certificateListAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_certificateListAncestorAdded

    public JButton getBtAssinar() {
        return btAssinar;
    }

    public JButton getBtCancelar() {
        return btCancelar;
    }

    public JList getCertificateList() {
        return certificateList;
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAssinar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JList certificateList;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
